Feat/#15 joinussection
LHA-Labs/lha-labs pull request #45
Opened 2024-03-25 11:12 UTC by cyntiche

2024-03-25 12:14 UTC, cyntiche commented
![image](https://github.com/LHA-Labs/lha-labs/assets/92375965/a0766692-9556-4586-803e-1f6fdde1aad1)

2024-03-25 12:37 UTC, cyntiche commented
![image](https://github.com/LHA-Labs/lha-labs/assets/92375965/fe70b4c5-8522-475b-b647-7b040ffa6eaa)

2024-04-02 22:40 UTC, Tchakoumi requested changes

2024-04-02 22:40 UTC, Tchakoumi commented on apps/donate/pages/AboutUs/JoinUsSection.tsx
> +      />
Instead of using an image, set the images as background image to the box. like

```ts
sx={{
      background: "url('/assets/landing_cta_bg.png')",
      boxShadow: 'inset 0 0 0 2000px rgba(165, 0, 0, 0.45)',
      backgroundSize: 'cover',
      backgroundRepeat: 'no-repeat',
  }}
```

2024-04-02 22:40 UTC, Tchakoumi commented on apps/donate/pages/AboutUs/JoinUsSection.tsx
> +          sx={{ borderRadius: '50px' }}
based on the theme file, this is no longer required

2024-04-02 22:40 UTC, Tchakoumi commented on apps/donate/pages/AboutUs/JoinUsSection.tsx
> +            width: '800px',
do not statically set item widths, except it's absolute case

2024-04-02 23:00 UTC, Tchakoumi submitted a review, later dismissed

2024-04-04 02:21 UTC, Tchakoumi requested changes

2024-04-04 02:21 UTC, Tchakoumi commented on apps/donate/pages/AboutUs/OurMissionVisionSection.tsx
- move this component to the components folder in about-us/tenets
- rename component to `LhaTenets.tsx`

2024-04-04 02:38 UTC, Tchakoumi approved these changes

2024-04-04 02:38 UTC, merged