Feat/#10 lha presentation section
LHA-Labs/lha-labs pull request #47
Opened 2024-03-25 11:13 UTC by cyntiche

2024-03-25 12:40 UTC, cyntiche commented
![image](https://github.com/LHA-Labs/lha-labs/assets/92375965/b9b68b12-6ccf-467a-98ae-ad5d032015ad)

2024-03-26 21:42 UTC, Tchakoumi requested changes

2024-03-26 21:42 UTC, Tchakoumi commented on apps/donate/pages/AboutUs/LhaPresentationSection.tsx
- [ ] rename to aboutUsPageHeader
- [ ] translate all texts in the files
- [ ] the page name does not match. should be ``pages/about-us/index.tsx``

2024-03-26 21:42 UTC, Tchakoumi commented on apps/donate/pages/AboutUs/LhaPresentationSection.tsx
> +          <Typography variant="body1" color="primary">
``<Typography >`` is by default `variant='body1'` you don't have to precise it.

2024-03-26 21:42 UTC, Tchakoumi commented on apps/donate/pages/AboutUs/LhaPresentationSection.tsx
> +  }
Move this interface out of the component.
This is because this component can be used elsewhere later on and you'll have to export it in that case.
right now, it is not exportable.

2024-03-26 21:42 UTC, Tchakoumi commented on apps/donate/pages/AboutUs/LhaPresentationSection.tsx
> +    quantity: string;
Quantity cannot be a string. only number

2024-03-26 21:42 UTC, Tchakoumi commented on apps/donate/pages/AboutUs/LhaPresentationSection.tsx
> +    nature: string;
change ~nature~ to `label` as it is not only more meaningful but representative of it's usage

2024-03-26 21:42 UTC, Tchakoumi commented on apps/donate/pages/AboutUs/LhaPresentationSection.tsx
> +                {quantity}{' '}
use template literals here...
 do
 
 ```ts
 {` ${quantity} `}
 ```

2024-03-26 21:42 UTC, Tchakoumi commented on apps/donate/pages/AboutUs/LhaPresentationSection.tsx
> +                  {nature}{' '}
Template literal

2024-03-26 21:42 UTC, Tchakoumi commented on apps/donate/pages/AboutUs/LhaPresentationSection.tsx
>  import imgOfTeam2 from '../../assets/imgOfTeam2.png';
put this images in `/donate/public/assets`
so that you can access them directly on the `Image` tag without importing them

2024-03-26 21:42 UTC, Tchakoumi commented on libs/theme/src/languages/en-us/website.ts
> +  donsReçu: "donations Received",
keys should be in english

2024-03-26 21:42 UTC, Tchakoumi commented on libs/theme/src/languages/en-us/website.ts
>    descriptionLorrain: 'At Let’s help Association, our mission is to empower lives through compassionate initiatives. By promoting education and fostering sustainable solutions, we envision a brighter
This data should come from a backend, it should be found in this file

2024-03-26 21:42 UTC, Tchakoumi commented on libs/theme/src/languages/fr/website.ts
>    descriptionLorrain: "À l'association Let's help, notre mission est d'améliorer les conditions de vie grâce à des initiatives empreintes de compassion. En promouvant l'éducation et en encourageant l
This data should come from a backend, it should be found in this file

2024-03-26 21:42 UTC, Tchakoumi commented on libs/theme/src/languages/fr/website.ts
> +  donsReçu: "Dons Reçu",
keys should be in english

2024-04-02 22:10 UTC, Tchakoumi approved these changes

2024-04-02 22:11 UTC, merged