Feat/#9 create our team section
LHA-Labs/lha-labs pull request #48
Opened 2024-03-25 11:13 UTC by cyntiche

2024-03-25 12:42 UTC, cyntiche commented
![image](https://github.com/LHA-Labs/lha-labs/assets/92375965/ddf41d19-6cce-4372-b455-9825dcc28978)

2024-03-26 21:57 UTC, Tchakoumi requested changes

2024-03-26 21:57 UTC, Tchakoumi commented on apps/donate/pages/AboutUs/OurTeamSection.tsx
> +    // },
every unused code should be gotten rid of before requesting a pr

2024-03-26 21:57 UTC, Tchakoumi commented on apps/donate/pages/AboutUs/OurTeamSection.tsx
> +                // height={activeMember.image.height}
unnecessary code should be removed

2024-03-26 21:57 UTC, Tchakoumi commented on apps/donate/pages/AboutUs/OurTeamSection.tsx
> +        )} */}
unnecessary code should be removed

2024-03-26 21:57 UTC, Tchakoumi commented on apps/donate/pages/AboutUs/OurTeamSection.tsx
> +      >
This box is useless if it holds nothing

2024-03-26 21:57 UTC, Tchakoumi commented on apps/donate/pages/AboutUs/OurTeamSection.tsx
> +                  >
instead use `<Typography component='a' ...>`

2024-03-26 21:57 UTC, Tchakoumi commented on apps/donate/pages/AboutUs/OurTeamSection.tsx
>      { icon: <LinkedInIcon />, link: 'lien_linkedin' },
material icons should be gotten rid of

2024-03-26 21:57 UTC, Tchakoumi commented on apps/donate/pages/AboutUs/OurTeamSection.tsx
the pages folder is used for routing, so no component file should be found in there.
components are found in ``donate/components` folder

move all components to ``donate/components`` folder

2024-03-26 21:57 UTC, Tchakoumi commented on apps/donate/pages/AboutUs/OurTeamSection.tsx
>  import LorrainPic from '../../assets/LorrainPic.png';
set images in `/donate/public/assets` folder and used ref instead of importing

2024-03-26 21:57 UTC, Tchakoumi commented on apps/donate/pages/AboutUs/OurTeamSection.tsx
>      { icon: <LinkedInIcon />, link: 'lien_linkedin' },
get rid of mui icons

2024-03-26 21:57 UTC, Tchakoumi commented on apps/donate/pages/AboutUs/OurTeamSection.tsx
> +          },
all of these vars are unused... 
what's the essence then?

2024-04-02 22:14 UTC, Tchakoumi submitted a review, later dismissed

2024-04-02 22:15 UTC, Tchakoumi commented
This PR is resolved in #10  before merge.
So I'll close it.

2024-04-02 22:15 UTC, closed without merging